version: ci-{build}
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
build_script:
- pwsh: >-
    $version = $env:APPVEYOR_BUILD_VERSION
    $versionSuffix = If ($env:APPVEYOR_REPO_TAG -eq "true") {""} Else {"--version-suffix=$($version)"}
    dotnet build -c Release $versionSuffix
    dotnet pack src/PingPongr -c Release --no-build --include-symbols $versionSuffix
    dotnet pack src/PingPongr.Extensions.AspNetCore -c Release --no-build --include-symbols $versionSuffix
    dotnet pack src/PingPongr.Serialization.JsonNet -c Release --no-build --include-symbols $versionSuffix
test_script:
- cmd: dotnet test src/PingPongr.Tests --no-build
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: Jg9KJHNi1aU36yFT+e50WsobFAuJxJUY1Z76TwEOPoKfMt+2+n0YeAUDa2Jiw3SS
  on:
    branch: master