version: ci-{build}
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
build_script:
- pwsh: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
      dotnet build -c Release
    }
    else {
      dotnet build -c Release --version-suffix $env:APPVEYOR_BUILD_VERSION
    }
test_script:
- cmd: dotnet test src/PingPongr.Tests --no-build
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: Jg9KJHNi1aU36yFT+e50WsobFAuJxJUY1Z76TwEOPoKfMt+2+n0YeAUDa2Jiw3SS
  on:
    branch: master